pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage('Completed') {
            steps {
                echo 'Job complete!'
            }
        }
        stage('Post Completion') {
            steps {
                echo 'Lining up Post Completion Tasks...'
            }
        }
        stage('Deploy To Dev') {
            steps {
                echo 'Deploying to Dev'
            }
        }
        stage('Deploy To Prod') {
            steps {
                echo 'Deploying to Prod'
            }
        }
        stage('Completion') {
            steps {
                echo 'Deployment completed'
                sh 'hostname'
            }
        }
    }
}
